version: '3.7'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-frontenvoy
    networks:
      envoy-redis-network:
        ipv4_address: 172.18.0.6
    expose:
      - "1999"
      - "9901"
    ports:
      - "1999:1999"
      - "9901:9901"

  redis: &redis
    image: redis:latest
    networks:
      envoy-redis-network:
        ipv4_address: 172.18.0.2
    expose:
      - "6379"

  redis-1:
    <<: *redis
    networks:
      envoy-redis-network:
        ipv4_address: 172.18.0.3
  
  redis-2:
    <<: *redis
    networks:
      envoy-redis-network:
        ipv4_address: 172.18.0.4
  
  redis-3:
    <<: *redis
    networks:
      envoy-redis-network:
        ipv4_address: 172.18.0.5
  
  redis-4:
    <<: *redis
    command: "redis-server --requirepass \"nt201412\""
    networks:
      envoy-redis-network:
        ipv4_address: 172.18.0.7
    ports:
      - "6380:6379"

networks:
  envoy-redis-network: 
    ipam:
        config:
        - subnet: 172.18.0.0/16